#!/usr/bin/env python3
"""build_countries_ts.py — consume data/countries.master.json and emit
src/lib/data/countries.ts. Non-destructive, re-runnable, no network."""
import json, os, re

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
with open(os.path.join(ROOT, "data", "countries.master.json"), encoding="utf-8") as f:
    countries = json.load(f)

body = json.dumps(countries, ensure_ascii=False, indent=2)
body = re.sub(r'^( *)"([a-zA-Z_][a-zA-Z0-9_]*)":', r"\1\2:", body, flags=re.M)
out = (
    "// AUTO-GENERATED by scripts/build_countries_ts.py — do not edit by hand.\n"
    "// Identity fields from ISO 3166-1. Admissions fields default to 'Doğrulama gerekli'.\n"
    'import type { Country } from "@/lib/types";\n\n'
    f"export const countries: Country[] = {body};\n"
)
path = os.path.join(ROOT, "src", "lib", "data", "countries.ts")
with open(path, "w", encoding="utf-8") as f:
    f.write(out)
print(f"[build_countries_ts] {len(countries)} ülke -> src/lib/data/countries.ts")
