#!/usr/bin/env python3
"""export_universities.py — merge data/ingested/universities.*.json batches into
src/lib/data/universities/generated/<cc>.ts (+ index.ts).

NON-DESTRUCTIVE: writes only the generated/ tree. Curated overrides in
src/lib/data/universities/_curated.ts always win at runtime and are never touched.
No network."""
from __future__ import annotations
import os, re, json, glob, ingest_common as ic

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
ING = os.path.join(ROOT, "data", "ingested")
GEN = os.path.join(ROOT, "src", "lib", "data", "universities", "generated")
HEADER = ('// AUTO-GENERATED by scripts/export_universities.py — do not edit by hand.\n'
          '// Curated records in ../_curated.ts always win.\n'
          'import type { University } from "@/lib/types";\n\n')

def ts_object(records):
    body = json.dumps(records, ensure_ascii=False, indent=2)
    return re.sub(r'^( *)"([a-zA-Z_][a-zA-Z0-9_]*)":', r"\1\2:", body, flags=re.M)

def main():
    files = sorted(glob.glob(os.path.join(ING, "universities.*.json")))
    if not files:
        print("data/ingested/ boş. Önce ingest_universities.py çalıştır."); return
    os.makedirs(GEN, exist_ok=True)
    batches = []
    for fp in files:
        cc = os.path.basename(fp).split(".")[1]
        recs = ic.load_json(fp, [])
        const = f"universities_{cc}"
        with open(os.path.join(GEN, f"{cc}.ts"), "w", encoding="utf-8") as f:
            f.write(HEADER + f"export const {const}: University[] = {ts_object(recs)};\n")
        batches.append((cc, const, len(recs)))
    lines = [HEADER]
    for cc, const, _ in batches:
        lines.append(f'import {{ {const} }} from "./{cc}";')
    lines.append("")
    lines.append("export const generatedUniversities: University[] = [" +
                 ", ".join("..." + const for _, const, _ in batches) + "];")
    with open(os.path.join(GEN, "index.ts"), "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    total = sum(n for _, _, n in batches)
    print(f"[export] {len(batches)} ülke batch'i, {total} kurum -> generated/*.ts")

if __name__ == "__main__":
    main()
