#!/usr/bin/env python3
"""export_programs.py — merge extracted programs into
src/lib/data/programs/generated/index.ts. NON-DESTRUCTIVE: curated programs in
_curated.ts always win at runtime. No network."""
from __future__ import annotations
import os, re, json, ingest_common as ic

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
def main():
    recs = ic.load_json(os.path.join(ROOT, "data", "ingested", "programs.extracted.json"), [])
    body = json.dumps(recs, ensure_ascii=False, indent=2)
    body = re.sub(r'^( *)"([a-zA-Z_][a-zA-Z0-9_]*)":', r"\1\2:", body, flags=re.M)
    out = ('// AUTO-GENERATED by scripts/export_programs.py — do not edit by hand.\n'
           '// Curated programs in ../_curated.ts always win.\n'
           'import type { Program } from "@/lib/types";\n\n'
           f"export const generatedPrograms: Program[] = {body};\n")
    path = os.path.join(ROOT, "src", "lib", "data", "programs", "generated", "index.ts")
    with open(path, "w", encoding="utf-8") as f:
        f.write(out)
    print(f"[export] {len(recs)} program -> programs/generated/index.ts")

if __name__ == "__main__":
    main()
